### ISSUE TITLE
Website background XSS_Powered by

### ISSUE THREAD

**Issue by crow821** [iqismart/xiuno-pro#1]
After installing xino-pro4 After 1.2, there is a storage XSS on the left side of the bottom of the background setting

Then in http://127.0.0.1/xiuno/admin/ Continue to log in to the administrator background and http://127.0.0.1/xiuno/admin/?setting -base. Htm setting page custom setting information:
![image](https://user-images.githubusercontent.com/39254463/168019039-3690a4a9-fd57-4e3c-8a24-e2926e9fec6e.png)
Modify the powered by xiuno pro to < script > alert ('Hello crow ') < / script >
![image](https://user-images.githubusercontent.com/39254463/168019178-936eaa32-6142-48c0-9639-502e6a5a459a.png)

Direct access http://127.0.0.1/xiuno/ , and close the browser cache and refresh the page. At this time, the XSS code is executed successfully:
![image](https://user-images.githubusercontent.com/39254463/168019216-10d165fb-4de3-46d6-82c6-bf01e3c37fd9.png)

![image](https://user-images.githubusercontent.com/39254463/168019123-41e90431-62bf-40f3-b7b4-3a77ac710086.png)

**Comment by toocruel** [comment]
background setting is only can used by admin, so unimportant!
